### PR TITLE
docs: add description and metabase query in catalog_stats

### PR DESCRIPTION
**Pull request by astagi**
This PR adds some useful Metabase queries and some doc for catalog_stats.

### CODE REVIEW

**Review by libremente — APPROVED** [review]
Thanks @astagi! :rocket:

**Comment by sebbalex** [comment]
I'm not particularly convinced to have the metabase queries directly in the code, we can create a `CATALOG.md` file in `engines` folder instead and be more detailed. Thoughts @astagi ?

**Comment by astagi** [comment]
> I'm not particularly convinced to have the metabase queries directly in the code, we can create a `CATALOG.md` file in `engines` folder instead and be more detailed. Thoughts @astagi ?

Agree with you @sebbalex

**Comment by astagi** [comment]
@sebbalex CATALOG.md is alive 🧟

**Review by sebbalex — APPROVED** [review]
:rocket:

**Pull request merged**
