### PR TITLE
[#17] handle socket.timeout exception and retry

### LINKED ISSUE #17: Timeout fetching google analytics data
**Describe the bug**
In last five days we are facing to this timeout

**Log**
```
2020-11-18 02:38:43,041 - ganalytics - INFO - Getting num visits...
2020-11-18 02:38:43,041 - ganalytics - INFO - Not authenticated, authenticating...
2020-11-18 02:38:43,041 - ganalytics - INFO - Authenticating to Google using service account
2020-11-18 02:38:43,041 - ganalytics - INFO - Getting google service
2020-11-18 02:38:43,319 - ganalytics - INFO - Getting google profile_id
Traceback (most recent call last):
  File "/opt/ingestion_scripts/devitalia/fetch-engines/main.py", line 75, in <module>
    compute_stats(args)
  File "/opt/ingestion_scripts/devitalia/fetch-engines/main.py", line 16, in compute_stats
    stats = engine.compute_stats()
  File "/opt/ingestion_scripts/devitalia/fetch-engines/engines/engine.py", line 71, in compute_stats
    method_to_call()
  File "/opt/ingestion_scripts/devitalia/fetch-engines/engines/ganalytics_stats.py", line 219, in unique_visits
    self.user_views = self._get_user_views()
  File "/opt/ingestion_scripts/devitalia/fetch-engines/engines/ganalytics_stats.py", line 202, in _get_user_views
    results = self._api_call(metrics=metrics)
  File "/opt/ingestion_scripts/devitalia/fetch-engines/engines/ganalytics_stats.py", line 181, in _api_call
    calldata = service.data().ga().get(
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/http.py", line 892, in execute
    resp, content = _retry_request(
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/http.py", line 204, in _retry_request
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/google_auth_httplib2.py", line 200, in request
    response, content = self.http.request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1948, in request
    (response, content) = self._request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1621, in _request
    (response, content) = self._conn_request(
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1560, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

### PR DESCRIPTION
**Pull request by sebbalex**
Fixes #17 

We should consider to use batch mode if supported from [current API](https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/service-py) or switch to [Analytics Reporting V4 API](https://developers.google.com/analytics/devguides/reporting/core/v4/samples)
See also [here](https://google-api-client-libraries.appspot.com/documentation/analytics/v3/python/latest/#new_batch_http_request)
v3 -> v4 [migration](https://developers.google.com/analytics/devguides/reporting/core/v4/migration#v4)

### CODE REVIEW

**Comment by bfabio** [comment]
Should we consider adding a certain number of retries for the same date? We risk running indefinitely if we always hit a timeout

**Comment by sebbalex** [comment]
> Should we consider adding a certain number of retries for the same date? We risk running indefinitely if we always hit a timeout

Yes, you right, I have added a simple limit, but I'm not sure if we should check also rate limit, it could fall in loop too. wdyt?

**Comment by bfabio** [comment]
Right now we rescue `googleapiclient.errors.HttpError` and I guess that can be caused by a number of reasons, but when we are sure we are being rate limited I see nothing wrong in just waiting and try again.

Can we get the information they are rate limiting from the response?

**Comment by sebbalex** [comment]
I tried to figured it out from docs but no success so far...

**Review by bfabio — APPROVED** [review]
:+1:

**Pull request merged**
